PeterLucido/SHAPESHIFT-back-end

models/day.js

write out the models

---

routes/days.js

create routes for days

---

controllers/days.js

create show controller ya hurd

create show controller

---

controllers/days.js

create update function

---

controllers/days.js

create delete function

---

routes/days.js
server.js

import days routes

---

controllers/days.js
routes/days.js

comment out create note route and add js to controller imports

---

controllers/days.js

write the createNote function

---

controllers/days.js

create sleep function

---

controllers/days.js

write the createMeal function

---

controllers/days.js

create the exercise function

---

controllers/days.js

updateNote function

---

controllers/days.js

write the update sleep function

write the update sleep function

---

controllers/days.js

write the updateMeal function and export updateSleep

write the updateMeal function and export updateSleep

---

controllers/days.js

write updateExercise function

---

controllers/days.js

add owner property to show the index of the owners days only

add owner property to show the index of the owners days only

---

controllers/days.js

edit controller function

---

controllers/days.js

update index function to show just the owners days

update index function to show just the owners days

---

controllers/days.js

fix index function

---

models/profile.js

add days to profile Schema

---

models/day.js

change the text to content in the schema
